### ISSUE TITLE
Add dataset notebooks to documentation

### ISSUE THREAD

**Issue by Peter9192** [phenology/springtime#100]
Add the notebooks that are currently in the main branch (`mk_data_exploration_...`) to the documentation page of 'datasets'.

**Comment by Peter9192** [comment]
Is it because there are so many figures? Or is the size of the figures too large? Perhaps we can modify the notebooks such that we only include a few key figures?

**Comment by SarahAlidoost** [comment]
> Is it because there are so many figures? Or is the size of the figures too large? Perhaps we can modify the notebooks such that we only include a few key figures?

Both the number of figures and the size of the figures make the total size of the notebook large. I modify the notebooks and docs in #105.
