### ISSUE TITLE
drop PyPhenologyDataset? or add docs

### ISSUE THREAD

**Issue by sverhoeven** [phenology/springtime#116]
The https://github.com/phenology/springtime/blob/main/src/springtime/datasets/pyphenology.py#L21 class is not documented in docs.
Would be nice to mention it.

**Comment by sverhoeven** [comment]
Or drop the class as it is very different to other datasets. Its static.

**Comment by Peter9192** [comment]
Makes sense, let's do it.

**Comment by Peter9192** [comment]
Would be nice to have an alternative sample dataset for springtime
