### ISSUE TITLE
Geometry is not added to `pyphenology` dataset

### ISSUE THREAD

**Issue by SarahAlidoost** [phenology/springtime#118]
Geometry is not added to `pyphenology` dataset, because in function `temperature_only_data_prep`, columns `longitude` and `latitude` are not selected, see [here](https://github.com/sdtaylor/pyPhenology/blob/2a58654126170eb304c71c5d453745c66058bd83/pyPhenology/models/utils/misc.py#L46).

_Originally posted by @SarahAlidoost in https://github.com/phenology/springtime/issues/108#issuecomment-1508698611_

**Comment by sverhoeven** [comment]
Refs #140
