### ISSUE TITLE
Define specifics of prototype workflow

### ISSUE THREAD

**Issue by Peter9192** [phenology/springtime#123]
We need an area (specified as a bounding box) that has several (say, 15) NPN stations which are covered by more than one MODIS and Daymet pixels. 

Furthermore, we need:
- One (or more) species or family of interest
- List of variables/bands/products of interest from MODIS and DayMet.

**Comment by khzadeh** [comment]
dataset: rnpn
    functional_type: "Deciduous broadleaf"  # multiple species
    phenophase: [371,373]  # breaking leaf buds (371,373)
    years: [2007, 2018]
    area:
      name: Washington # 500km boundingbox centered at latitude: 47.751076 and longitude: -120.740135
      bbox: [-124.08406940413612,45.50277198520317,-117.39620059586387,49.99938001479683]

**Comment by Peter9192** [comment]
See https://github.com/phenology/springtime/blob/main/src/springtime/recipes/model_comparison_usecase.yaml
