### ISSUE TITLE
Generate API documentation

### ISSUE THREAD

**Issue by sverhoeven** [phenology/springtime#149]
The code has lots of docstrings it would be nice to see them renderend somewhere like the mkdir api docs.

**Comment by Peter9192** [comment]
There's also examples in notebooks for each of the datasets. Might want to limit duplication as it's hard to maintain. Note these can also double as tests.

**Comment by Peter9192** [comment]
Mkdocstrings uses a python handler. There's a legacy handler based on pytkdocs and a newer handler based on griffe, where pydantic support is still on the todo list. There's been several issues relating to how we use our (typically pydantic) classes, e.g. related to inhering from parents, using class attributes/fields, etc. that have only partly been solved

https://github.com/mkdocstrings/griffe/pull/170
https://github.com/mkdocstrings/pytkdocs/issues/123
https://github.com/mkdocstrings/pytkdocs/issues/9

Note that attributes documented in the class docstring are formatted much nicer than attributes documented inline:

![image](https://github.com/phenology/springtime/assets/17080502/808a8423-d3e4-41ee-a1e0-07004a71cec0)
versus
![image](https://github.com/phenology/springtime/assets/17080502/b69d3f1a-33c2-4924-92f2-4b3f2b4aff8e)

**Comment by Peter9192** [comment]
TODO:

- Add example recipes (yaml) to docstrings
- See if we can run examples somehow to include output in the API docs.
