### ISSUE TITLE
Concluding recipe execution

### ISSUE THREAD

**Issue by Peter9192** [phenology/springtime#155]
There are some options:

1. The recipe only has datasets section
    In this case it downloads the data and applies specified/standard preprocessing (if it's not already available).
2. The recipe has datasets and experiments section
    In this case it should save comparison figures, and export the scores, and save each of the trained models
3. Recipe that loads new data and makes predictions with a saved model

**Comment by sverhoeven** [comment]
Data from datasets is saved to /tmp/output/save.csv 
For example running src/springtime/recipes/model_comparison_usecase.yaml gives csv with header
`year,geometry,breaking leaf buds_doy,tmin_1,tmin_2,tmin_3,tmin_4,tmin_5,tmin_6,tmin_7,tmin_8,tmin_9,tmin_10,tmin_11,tmin_12,tmax_1,tmax_2,tmax_3,tmax_4,tmax_5,tmax_6,tmax_7,tmax_8,tmax_9,tmax_10,tmax_11,tmax_12,Fpar_500m_1,Fpar_500m_2,Fpar_500m_3,Fpar_500m_4,Fpar_500m_5,Fpar_500m_6,Fpar_500m_7,Fpar_500m_8,Fpar_500m_9,Fpar_500m_10,Fpar_500m_11,Fpar_500m_12,Lai_500m_1,Lai_500m_2,Lai_500m_3,Lai_500m_4,Lai_500m_5,Lai_500m_6,Lai_500m_7,Lai_500m_8,Lai_500m_9,Lai_500m_10,Lai_500m_11,Lai_500m_12`

**Comment by Peter9192** [comment]
After #192 springtime recipes no longer contain experiments.
