### ISSUE TITLE
Setup benchmark cases

### ISSUE THREAD

**Issue by Peter9192** [phenology/springtime#16]
Following up on #4, it would be good to extend our prototypes so that we capture actual use cases, i.e. apply the models in a real-world practical example. That means we need to download actual data (instead of the test data from pyphenology) and also use the trained/evaluated model to make an actual prediction. There are multiple types of predictions (space/time, etc.) and I think it makes sense to define a separate prototype or "benchmark" case for each of them. For example:

1. Train a (ML) model with day of first bloom from pheno observations as target and weather data as predictors. The observations are available for a few locations, whereas the weather data is available on a full raster. So, we want to apply the model for the full raster. In this case, we do not necessarily want to predict ahead-of-time (i.e. forecast), so the weather data may span the whole year, "including" the day of first bloom.
2. Train a (ML) model with day of first bloom from pheno observations as target and weather data as predictors. In this case, only use weather data from e.g. January, i.e. far before the expected event date. In this case, we want to forecast ahead-of-time when the event will happen in another year.

For now, the model may be very simple. Later on, we may try with different models/settings/inputs, etc. The goal is to have a clear benchmark usecase.

I suggest we start with a simple weather data set from e.g. e-obs or daymet, using monthly mean temperature or something like that.

**Comment by Peter9192** [comment]
If would could use the same syntax as OpenML, we might be able to use it in the future. I think in OpenML lingo what we're trying to do here is referred to as a ['task'](https://www.openml.org/search?type=task).

Also see their [API examples](https://www.openml.org/apis), e.g.:

```py
from sklearn import ensemble
from openml import tasks, runs

# Build any model you like
clf = ensemble.RandomForestClassifier()

# Download any OpenML task
task = tasks.get_task(3954)

# Run and evaluate your model on the task
run = runs.run_model_on_task(clf, task)

# Share the results on OpenML. Your API key can be found in your account.
# openml.config.apikey = 'YOUR_KEY'
run.publish()
```

**Comment by SarahAlidoost** [comment]
Issues to be discussed for usecase 1:
1. ML problem definition: features and samples
2. statistics used for weather data (for both training and prediction purposes): weather data often have finer temporal resolutions than pheno observations (one value per year).
3. land cover mask: weather data are continuous in space whereas pheno data are related to a region. A landcover map is needed to mask the ML output. 
5. data organization: the use of pandas dataframes and xarray datasets

**Comment by Peter9192** [comment]
Now we have 
https://github.com/phenology/springtime/tree/main/src/springtime/recipes
