### ISSUE TITLE
Document use of docker container

### ISSUE THREAD

**Issue by Peter9192** [phenology/springtime#168]
Also include

- How to mount directories
- Maybe change the configuration to not write in a temporary directory?
-

**Comment by Peter9192** [comment]
Perhaps we could also base our docker image on

https://jupyter-docker-stacks.readthedocs.io/en/latest/using/selecting.html#jupyter-r-notebook

**Comment by Peter9192** [comment]
https://jupyter-docker-stacks.readthedocs.io/en/latest/using/recipes.html#using-mamba-install-or-pip-install-in-a-child-docker-image

**Comment by sverhoeven** [comment]
Fixed in #170
