### ISSUE TITLE
Edit links in readthedocs incorrect

### ISSUE THREAD

**Issue by sverhoeven** [phenology/springtime#180]
For example on https://springtime.readthedocs.io/en/latest/ the edit link is https://github.com/phenology/springtime/edit/master/docs/index.md while it should be https://github.com/phenology/springtime/edit/main/docs/index.md

For example on https://springtime.readthedocs.io/en/latest/notebooks/datasets_npn/ the edit link is https://github.com/phenology/springtime/edit/master/docs/notebooks/datasets_npn.ipynb while it should be https://github.com/phenology/springtime/edit/main/docs/notebooks/datasets_npn.ipynb

After #164 is merged

On http://127.0.0.1:8000/reference/springtime/datasets/insitu/pep725/ edit link is https://github.com/phenology/springtime/edit/master/docs/src/springtime/datasets/insitu/pep725.py
while it should be https://github.com/phenology/springtime/edit/main/src/springtime/datasets/insitu/pep725.py

On http://127.0.0.1:8000/clireference/insitu/NPN/ edti link is 
https://github.com/phenology/springtime/edit/master/docs/src/springtime/recipes/datasets/insitu/NPN.yaml
while it should be https://github.com/phenology/springtime/edit/main/src/springtime/recipes/datasets/insitu/NPN.yaml

Notice that the branch should be main instead of master.

Notice that docs/ should removed from edit link when item is not inside docs/ folder.

**Comment by Peter9192** [comment]
We discussed that we could also remove the button, I don't think there's a big need for it. For notebooks, the download button is more useful, and if you just want to go to the GH repo, you can use the top right icon in the menu bar.
