### ISSUE TITLE
Underscore in the package name py_ppo

### ISSUE THREAD

**Issue by SarahAlidoost** [phenology/springtime#25]
The package `py_ppo` will be installed in the `springtime` environment as `py-ppo`. The reason is that `pip` replaces underscores with dashes. However, it is used as `import py_ppo`. PEP8 discourages the use of underscore, see [package-and-module-names](https://peps.python.org/pep-0008/#package-and-module-names).

**Comment by Peter9192** [comment]
You're right, though the guidelines also say: 

> Underscores can be used in the module name if it improves readability

I think this applies here. Do you think `pyppo` is better?

**Comment by SarahAlidoost** [comment]
> You're right, though the guidelines also say:
> 
> > Underscores can be used in the module name if it improves readability

 I also read this but I disagree with it. I found it confusing because now different names are used to install/uninstall and import a package. Perhaps they make a distinction between a module and a package name.

> I think this applies here. Do you think `pyppo` is better?

I amnot sure, I used `pydaymet`, but perhaps we can find better names for both packages.

**Comment by Peter9192** [comment]
Okay. Feel free to change it for now if you find it annoying. The names are not set in stone yet

**Comment by Peter9192** [comment]
outdated
