### ISSUE TITLE
Support configuration in multiple ways

### ISSUE THREAD

**Issue by Peter9192** [phenology/springtime#44]
- default config
- override based on (partial) config file in standard location
- override based on (partial) config file in location passed through CLI/API
- override individual options through CLI or API

Perhaps use hydra https://hydra.cc/docs/intro/

**Comment by sverhoeven** [comment]
Now not ideal, as config fields are used on import time. 
You need to change configuration before importing things that use config.

**Comment by sverhoeven** [comment]
Use https://pypi.org/project/xdg-base-dirs/ to get cache and config dir
