### ISSUE TITLE
Create conda env file

### ISSUE THREAD

**Issue by sverhoeven** [phenology/springtime#54]
To install most R dependencies without compiling

**Comment by Peter9192** [comment]
Phenor and modistools are not available from anaconda channels, so I think we need a separate r-install command anyway. Would this also be an alternative?

```bash
# Create a basic conda environment with R and Python
mamba create -c conda-forge -n springtime python=3.9 r-base r-devtools

# Install r-deps
...

# Install python package and verify installation
pip install git+https://github.com/phenology/springtime.git
python -m r2py.situation
> ...
> Calling `R RHOME`: /home/peter/miniconda3/envs/springtime/lib/R
> Environment variable R_LIBS_USER: None
> ...


# Or use hatch
pip install hatch
hatch env create
hatch run python -m rpy2.situation
```

**Comment by Peter9192** [comment]
Perhaps [r-essentials](https://docs.anaconda.com/anaconda/packages/r-language-pkg-docs/#r-essentials-bundle) already contains the bulk of what we need?

**Comment by sverhoeven** [comment]
Maybe https://cran.r-project.org/web/packages/packrat/ can be used to make a lock file.
