### ISSUE TITLE
PPO: ppo_download

### ISSUE THREAD

**Issue by khzadeh** [phenology/springtime#68]
I tried to download a dataset that doesn't exist using the ppo download function. For example: "dataset = RPPO(genus="Syringa", termID="obo:PPO_0002032", limit=10, years=[2022, 2022])"

Although the results should have been empty and it shows the below message. the load function "dataset.load()"   loads the previous results. It seems that the temporary directory "/ppo_download/" hasn’t been removed. 

"no results found!
Warning message:
In unzip(tf, exdir = "~/ppo_download") :
  error 1 in extracting from zip file
ppo_download"

**Comment by Peter9192** [comment]
I noticed there's a typo in the source code of rppo here:

https://github.com/ropensci/rppo/blob/f2a5d216368121d9dd2545d026c3862a57280383/R/ppo_data.R#L221

"ppo_download" should be "~/ppo_download". I included a fix in https://github.com/ropensci/rppo/pull/20

**Comment by Peter9192** [comment]
Made https://github.com/ropensci/rppo/pull/21 where I attempt to fix the CI

**Comment by Peter9192** [comment]
> Made [ropensci/rppo#21](https://github.com/ropensci/rppo/pull/21) where I attempt to fix the CI

That's now merged
