### ISSUE TITLE
NPN: dataset.download

### ISSUE THREAD

**Issue by khzadeh** [phenology/springtime#69]
I tried to download data with this example: "dataset = NPNPhenor(species=36, phenophase=483, years=[2012, 2014])". It seems that there's no observation for the year 2014 and I get the following error when I call the "dataset.download()" function.

"RRuntimeError: Error in (function (species = 3, phenophase = 371, start = "2000-01-01",  : 
  Query returned no data, check your input parameters!"

**Comment by Peter9192** [comment]
A few remarks here:

- Indeed, many searches return empty, and this is (very) annoying. For lack of a better approach as of yet, I used https://data.usanpn.org/observations/get-started to find non-empty selections. 
- We could (or should) return a more helpful error message, for example pointing the the site above
- It would be good to look for a better solution in the long term

**Comment by Peter9192** [comment]
Might use https://github.com/usa-npn/rnpn/

**Comment by Peter9192** [comment]
Solved by using RNPN
