### ISSUE TITLE
Function to align/join data from different sources

### ISSUE THREAD

**Issue by Peter9192** [phenology/springtime#87]
We have temporal joining and spatial joining problems:
1. Some dataset use site id/names and others use lat,lon
1. modis return days since 1 jan 1970 while others return year + day of a year

**Comment by SarahAlidoost** [comment]
If `geometry` and `time` are available in two dataframes, spatial/temporal join can be done as:
```python
import geopandas
gdp_spatial = geopandas.sjoin_nearest(left_df, right_df, how="inner") # tested code
gdp_spatial.loc[lambda d: d["time_left"].eq(d["time_right"])] # not tested code
```
Do we still need a function for align/join? I think we need to standardize the columns perhaps in #92?

**Comment by Peter9192** [comment]
Perhaps we can use [`geopandas.resolve`](https://geopandas.org/en/stable/docs/user_guide/aggregation_with_dissolve.html)?

**Comment by Peter9192** [comment]
![image](https://user-images.githubusercontent.com/17080502/235447399-4cd39c55-177d-4461-808c-135b544b4ea7.png)

**Comment by sverhoeven** [comment]
Continue in https://github.com/phenology/springtime/issues/140
