### ISSUE TITLE
NPN get phenophases from species

### ISSUE THREAD

**Issue by Peter9192** [phenology/springtime#90]

**Comment by sverhoeven** [comment]
rnpn package has npn_phenophases_by_species  function see https://github.com/usa-npn/rnpn/blob/0dff444e4648b28b76e6748a4f970326364e8d7a/R/npn_phenophases.R#L71

**Comment by sverhoeven** [comment]
> rnpn package has npn_phenophases_by_species function see https://github.com/usa-npn/rnpn/blob/0dff444e4648b28b76e6748a4f970326364e8d7a/R/npn_phenophases.R#L71

rnpn uses tibble dataframes with nesting. Which need to be transformed to pandas dataframe. See #95

**Comment by sverhoeven** [comment]
> rnpn package has npn_phenophases_by_species function see https://github.com/usa-npn/rnpn/blob/0dff444e4648b28b76e6748a4f970326364e8d7a/R/npn_phenophases.R#L71

rnpn uses tibble dataframes with nesting. Which need to be transformed to pandas dataframe. See #95

**Comment by sverhoeven** [comment]
> rnpn package has npn_phenophases_by_species function see https://github.com/usa-npn/rnpn/blob/0dff444e4648b28b76e6748a4f970326364e8d7a/R/npn_phenophases.R#L71

rnpn uses tibble dataframes with nesting. Which need to be transformed to pandas dataframe. See #95

**Comment by Peter9192** [comment]
Bit less necessary now that we use rnpn which can download data for multiple species and phenophases
